name: Go Lint

on: [push]

jobs:
  test:
    name: Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
